# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(600, 40, 371, 341))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setBatchSize(100)
        self.listWidget.setObjectName("listWidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 551, 251))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_start_FTP = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_start_FTP.setGeometry(QtCore.QRect(50, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_FTP.setFont(font)
        self.pushButton_start_FTP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start_FTP.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_start_FTP.setObjectName("pushButton_start_FTP")
        self.pushButton_stop_FTP = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_stop_FTP.setEnabled(True)
        self.pushButton_stop_FTP.setGeometry(QtCore.QRect(270, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_stop_FTP.setFont(font)
        self.pushButton_stop_FTP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop_FTP.setStyleSheet("background-color: rgb(214, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_stop_FTP.setObjectName("pushButton_stop_FTP")
        self.label_start = QtWidgets.QLabel(self.groupBox_3)
        self.label_start.setGeometry(QtCore.QRect(60, 200, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_start.setFont(font)
        self.label_start.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_start.setObjectName("label_start")
        self.lineEdit_sourceFolder = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_sourceFolder.setEnabled(False)
        self.lineEdit_sourceFolder.setGeometry(QtCore.QRect(190, 40, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.lineEdit_sourceFolder.setFont(font)
        self.lineEdit_sourceFolder.setObjectName("lineEdit_sourceFolder")
        self.pushButton_sourceFolder = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_sourceFolder.setGeometry(QtCore.QRect(440, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_sourceFolder.setFont(font)
        self.pushButton_sourceFolder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sourceFolder.setStyleSheet("")
        self.pushButton_sourceFolder.setObjectName("pushButton_sourceFolder")
        self.label_souce_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_souce_2.setGeometry(QtCore.QRect(93, 80, 81, 31))
        self.label_souce_2.setObjectName("label_souce_2")
        self.lineEdit_HMIIP = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_HMIIP.setGeometry(QtCore.QRect(190, 80, 241, 31))
        self.lineEdit_HMIIP.setObjectName("lineEdit_HMIIP")
        self.label_souce_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_souce_3.setGeometry(QtCore.QRect(30, 130, 151, 31))
        self.label_souce_3.setObjectName("label_souce_3")
        self.lineEdit_exportFolder = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_exportFolder.setEnabled(False)
        self.lineEdit_exportFolder.setGeometry(QtCore.QRect(190, 130, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.lineEdit_exportFolder.setFont(font)
        self.lineEdit_exportFolder.setObjectName("lineEdit_exportFolder")
        self.pushButton_exportFolder = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_exportFolder.setGeometry(QtCore.QRect(440, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_exportFolder.setFont(font)
        self.pushButton_exportFolder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exportFolder.setStyleSheet("")
        self.pushButton_exportFolder.setObjectName("pushButton_exportFolder")
        self.label_souce_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_souce_4.setGeometry(QtCore.QRect(44, 40, 131, 31))
        self.label_souce_4.setObjectName("label_souce_4")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(660, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("background-color: rgb(83, 83, 83);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(730, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_exportOperation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exportOperation.setGeometry(QtCore.QRect(790, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exportOperation.setFont(font)
        self.pushButton_exportOperation.setStyleSheet("background-color: rgb(83, 83, 83);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_exportOperation.setObjectName("pushButton_exportOperation")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(10, 330, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reset.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "接続設定"))
        self.pushButton_start_FTP.setText(_translate("MainWindow", "リアルタイム接続"))
        self.pushButton_stop_FTP.setText(_translate("MainWindow", "リアルタイム接続停止"))
        self.label_start.setText(_translate("MainWindow", "==HMI接続中=="))
        self.pushButton_sourceFolder.setText(_translate("MainWindow", "選択"))
        self.label_souce_2.setText(_translate("MainWindow", "HMI IP："))
        self.label_souce_3.setText(_translate("MainWindow", "エクスポート選択："))
        self.pushButton_exportFolder.setText(_translate("MainWindow", "選択"))
        self.label_souce_4.setText(_translate("MainWindow", "インポート選択："))
        self.pushButton_clear.setText(_translate("MainWindow", "CLEAR"))
        self.label.setText(_translate("MainWindow", "操作履歴"))
        self.pushButton_exportOperation.setText(_translate("MainWindow", "エクスポート"))
        self.pushButton_reset.setText(_translate("MainWindow", "RESET"))

